import './js/header';
import './js/recipe-modal';
import './js/order-modal';
import './js/popular-recipes';
import './js/all-categories';
import './js/swiper';
import './js/swiper-api';
import './js/all-cards-api';
// import './js/search';
import './js/favorites';
import './js/scroll-up';
